name: uniform
description: A lightweight form library for Flutter that handles form validation and state management gracefully, with unified form representation.
version: 2.0.7
homepage: https://acmesoftware.com
repository: https://github.com/AcmeSoftwareLLC/uniform
issue_tracker: https://github.com/AcmeSoftwareLLC/uniform/issues
screenshots:
  - description: 'uniForm: A Flutter Form Library'
    path: images/uniform.png
topics:
  - form
  - validation
  - reactive
  - forms

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0